# Generated by Django 5.0 on 2023-12-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_period',
            field=models.IntegerField(verbose_name='Время на выполнение'),
        ),
    ]
