# Generated by Django 5.0 on 2023-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='Периодичность'),
        ),
    ]
